name: envprof

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  info:
    uses: idelchi/devenv/.github/workflows/info.yml@dev

  verify:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    uses: idelchi/devenv/.github/workflows/task.yml@dev
    needs: info

  next-tag:
    uses: idelchi/devenv/.github/workflows/next-tag.yml@dev
    if: github.ref == 'refs/heads/dev'
    needs: verify

  prerelease:
    uses: idelchi/devenv/.github/workflows/prerelease.yml@dev
    if: github.ref == 'refs/heads/dev'
    needs: next-tag
    permissions:
      contents: write
      actions: write
    with:
      tag: ${{ needs.next-tag.outputs.next }}-beta
      workflow: release
